### ISSUE TITLE
Progressbar breaks jline-enabled applications

### ISSUE THREAD

**Issue by voseldop** [ctongfei/progressbar#40] opened 2018-07-04 14:27 UTC
Progressbar creates new JLine Terminal and doesn't close it properly.

This causes corrupted input. checked with 0.7.0.
Doesn't happen with 0.5.5

**Comment by ctongfei** [comment] 2018-07-05 06:15
This seems to be related with JLine 3. See #31 which might be caused by similar problems.

I wonder how was the input corrupted? Can you provide me with code snippets / screenshots to further elaborate this problem?

**Comment by voseldop** [comment] 2018-07-06 10:28
The problem is Terminal building in ProgressBar thread.
Each progressbar thread creates new Terminal, which in fact spawns internally extra threads reading input. This terminal has to be closed, otherwise it will be stealing input.

**Comment by ctongfei** [comment] 2018-07-06 19:58
Does this line fix the problem?
https://github.com/ctongfei/progressbar/blob/master/src/main/java/me/tongfei/progressbar/ProgressBar.java#L142

**Comment by ctongfei** [comment] 2018-07-29 05:30
Fixed in version 0.7.1.

**Closed by ctongfei** 2018-07-29 05:30 UTC
Labels: jline, regression, terminal
